import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/Header'
import { headers } from 'next/headers'
import { clx } from '@/utilts'
import Modal from '@/components/containers/modal/Modal'
import { AppProviders } from '@/context/AppProviders'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers()
  const theme = headersList.get('x-theme')

  return (
    <html
      lang="en"
      className={clx(theme === 'dark' ? 'dark' : '', 'bg-gray-lightest-2 dark:bg-black')}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          <div className="bg-white dark:bg-black min-h-screen transition-all transition-duration-200">
            <Header />
            {children}
          </div>
          <Modal />
        </AppProviders>
      </body>
    </html>
  )
}
