import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/Header'
import { LanguageProvider } from '@/context/LanguageContext'
import { headers } from "next/headers";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const headersList = await headers()
  console.log("headersList.getSetCookie()", headersList.getSetCookie());

  const theme = headersList.get('x-theme')

  console.log("------> x-theme", theme);


  return (
    <html lang="en" className={theme === 'dark' ? 'dark' : ''}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-white dark:bg-gray-darkest min-h-screen transition-all transition-duration-200">
          <LanguageProvider>
            <Header />
            {children}
          </LanguageProvider>
        </div>
      </body>
    </html>
  )
}
